name = "FactoredMatrices"
uuid = "aa288701-83bc-4fd3-aba5-ac3dd7693cd5"
authors = ["JFdCD <j.cossio.diaz@gmail.com>"]
version = "2.0.3-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"
